### ISSUE TITLE
too! many! exclamations!

### ISSUE THREAD

**Issue by globau** [mozilla-conduit/lando-ui#22]
there's a large amount of exclamations! in the lando-ui.
imho all should be removed, including from error messages.

**Comment by purelogiq** [comment]
I only see one instance of an exclamation point (on the "Land this Revision!" button). Can you point out the others @globau?

**Comment by purelogiq** [comment]
Ahh on the home page! Nevermind!!!!!!

**Comment by globau** [comment]
and "Protected page! You must be logged in!"

**Comment by marti1125** [comment]
I will fix this :+1:
