### ISSUE TITLE
dates are incorrectly displayed as unix epoch seconds

### ISSUE THREAD

**Issue by globau** [mozilla-conduit/lando-ui#25]

**Comment by purelogiq** [comment]
We will need to add session based settings where the user can set their timezone preferences before displaying it in the correct time, yes?

**Comment by globau** [comment]
`new Date().getTimezoneOffset()`

**Comment by globau** [comment]
that said, if your epoch seconds are utc (which i hope they are!):

`new Date(1495638270 * 1000).toLocaleString()`

**Comment by purelogiq** [comment]
Or that! :)
