### ISSUE TITLE
lando dev instance links to production bugzilla

### ISSUE THREAD

**Issue by globau** [mozilla-conduit/lando-ui#29]
**Spengler**: There's something very important I forgot to tell you.
**Venkman**: What?
**Spengler**: Don't cross the streams.
**Venkman**: Why?
**Spengler**: It would be bad.
**Venkman**: I'm fuzzy on the whole good/bad thing. What do you mean, "bad"?
**Spengler**: Try to imagine all life as you know it stopping instantaneously and every molecule in your body exploding at the speed of light.
**Stantz**: Total protonic reversal!
**Venkman**: Right. That's bad. Okay. All right. Important safety tip. Thanks, Egon.

**Comment by purelogiq** [comment]
😰 😰 oops
