### ISSUE TITLE
dockerflow routes are being cached

### ISSUE THREAD

**Issue by purelogiq** [mozilla-conduit/lando-ui#51]
@ckolos Informed me that the dockerflow routes, e.g. /__lbheartbeat__ are returning 302 status codes. This shouldn't happen as those endpoints should always return fresh data.

- Add cache busting headers to the dockerflow routes.
- In the body add the current timestamp to ensure that the response changes each time and nothing in the network stack decides to cache the response.

**Comment by smacleod** [comment]
@purelogiq You can probably use what I'm doing for this, in the blueprint:
```
@dockerflow.after_request
def disable_caching(response):
    """Disable caching on a response and return it."""
    response.cache_control.no_cache = True
    response.cache_control.no_store = True
    response.cache_control.must_revalidate = True
    return response
```
